spring:
  thymeleaf:
    enabled: false
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  datasource:
    druid:
      primary:
        # mysql连接池的配置信息
        driverClassName: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://${DB_HOST}:${DB_PORT:3306}/${DB_NAME:abc_backend}?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8&useSSL=false
        username: ${DB_USERNAME:root}
        password: ${DB_PASSWORD:123456}
        initialSize: 5
        minIdle: 5
        maxActive: 20
        # 配置获取连接等待超时的时间
        maxWait: 60000
        # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
        timeBetweenEvictionRunsMillis: 60000
        # 配置一个连接在池中最小生存的时间，单位是毫秒
        minEvictableIdleTimeMillis: 300000
        validationQuery: SELECT 1 FROM DUAL
        testWhileIdle: true
        testOnBorrow: false
        testOnReturn: false
        # 打开PSCache，并且指定每个连接上PSCache的大小
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
        filters: stat,wall
        # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
        connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
        reset-enable: false
        url-pattern: /druid/*
        allow:
      web-stat-filter:
        enabled: true
        # 添加过滤规则
        url-pattern: /*
        # 忽略过滤格式
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,/ic-druid/*"
  jpa:
    #database: MYSQL
    show-sql: true
    hibernate:
      primary-dialect: org.hibernate.dialect.MySQL5InnoDBDialect
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  redis:
    host: ${REDIS_HOST:127.0.0.1}
    port: ${REDIS_PORT:6379}
    database: ${REDIS_DB:10}
    password: ${REDIS_PASSWORD:123456}
  session:
    redis:
      namespace: jcyy:admin:session
    timeout: 86400
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  data:
    redis:
      repositories:
        #不启用RedisRepositories
        enabled: false
  cache:
    #cache策略使用redis，开发时关闭cache使用none
    type: redis
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

#Server
server:
  port: 8889
  tomcat:
    uri-encoding: utf-8
    basedir: tmp

# 自定义日志配置文件名称
logging:
  config: classpath:logback-uat.xml
#线程
pool:
  #核心线程数
  core-size: 10
  #最大线程数
  max-size: 200
  #队列最大长度
  queue-capacity: 10
#upload path
upload:
  local:
    base-path: ../abc_resource/upload/
    base-url: /upload/
custom:
  config:
    ignores:
      get:
        - "/apis/v1/"
      # 需要过滤的 post 请求
      post:
        - "/api/auth/login"
        - "/api/auth/logout"
      # 需要过滤的请求，不限方法
      pattern:
        - "/test/*"

